In [1]:
import pandas as pd
import numpy as np
import json
import gzip

In [2]:
import torch

In [3]:
dataset_name = '500'

In [4]:
with gzip.open(f'Dataset/dataset_{dataset_name}.json.gz') as f:
    DATA = json.loads(f.read())
df = pd.DataFrame(DATA)
df

ts  bytes_out  pkts_out  bytes_in  pkts_in  \
0      1.592754e+09       3366        13      5427       10   
1      1.592715e+09       2542        11      4995       11   
2      1.592713e+09       3415        14      5102       11   
3      1.592755e+09       3341        15      7847       10   
4      1.592713e+09       3336        16     11718       12   
...             ...        ...       ...       ...      ...   
74995  1.593624e+09        195        32     76158       32   
74996  1.593183e+09        681        90    998763      144   
74997  1.593521e+09        465        36    348827       58   
74998  1.593512e+09       2649        15       671       14   
74999  1.592755e+09       1590         5       263        4   

                                                 packets  \
0      [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
1      [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
2      [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
3      [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
4      [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
...                                                  ...   
74995  [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
74996  [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
74997  [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
74998  [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   
74999  [{'t': 0.0, 'd': '>', 'l': 60, 'b': 0, 'iat': ...   

                                                  upload  \
0      [22, 3, 1, 2, 0, 1, 0, 1, 252, 3, 3, 53, 67, 1...   
1      [22, 3, 1, 2, 0, 1, 0, 1, 252, 3, 3, 76, 69, 1...   
2      [22, 3, 1, 2, 0, 1, 0, 1, 252, 3, 3, 66, 7, 12...   
3      [22, 3, 1, 2, 0, 1, 0, 1, 252, 3, 3, 134, 147,...   
4      [22, 3, 1, 2, 0, 1, 0, 1, 252, 3, 3, 172, 44, ...   
...                                                  ...   
74995  [71, 69, 84, 32, 47, 105, 109, 103, 47, 97, 10...   
74996  [71, 69, 84, 32, 47, 50, 48, 50, 48, 47, 48, 5...   
74997  [71, 69, 84, 32, 47, 50, 48, 50, 48, 47, 48, 5...   
74998  [22, 3, 1, 2, 0, 1, 0, 1, 252, 3, 3, 194, 184,...   
74999  [71, 69, 84, 32, 47, 97, 112, 105, 47, 111, 11...   

                                                download  \
0      [22, 3, 3, 0, 65, 2, 0, 0, 61, 3, 3, 103, 40, ...   
1      [22, 3, 3, 0, 84, 2, 0, 0, 80, 3, 3, 42, 124, ...   
2      [22, 3, 3, 0, 65, 2, 0, 0, 61, 3, 3, 242, 3, 1...   
3      [22, 3, 3, 0, 84, 2, 0, 0, 80, 3, 3, 216, 0, 7...   
4      [22, 3, 3, 0, 84, 2, 0, 0, 80, 3, 3, 179, 165,...   
...                                                  ...   
74995  [72, 84, 84, 80, 47, 49, 46, 49, 32, 50, 48, 4...   
74996  [72, 84, 84, 80, 47, 49, 46, 49, 32, 50, 48, 5...   
74997  [72, 84, 84, 80, 47, 49, 46, 49, 32, 50, 48, 5...   
74998  [22, 3, 3, 0, 94, 2, 0, 0, 90, 3, 3, 234, 115,...   
74999  [72, 84, 84, 80, 47, 49, 46, 49, 32, 50, 48, 4...   

                                                    upBD  \
0      [320, 31, 15, 34, 13, 16, 20, 14, 19, 18, 21, ...   
1      [319, 26, 20, 31, 15, 10, 10, 11, 19, 9, 15, 1...   
2      [317, 36, 19, 32, 18, 11, 20, 15, 16, 12, 11, ...   
3      [322, 31, 21, 31, 9, 17, 10, 10, 19, 16, 10, 1...   
4      [317, 29, 18, 31, 17, 22, 15, 8, 18, 11, 17, 1...   
...                                                  ...   
74995  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 6, 0, ...   
74996  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 19, 0...   
74997  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 13, 0...   
74998  [213, 19, 17, 44, 16, 14, 12, 14, 17, 7, 12, 4...   
74999  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 7, 0, ...   

                                                  downBD        dur  \
0      [109, 144, 67, 109, 89, 62, 117, 31, 32, 36, 2...   4.078236   
1      [113, 134, 64, 107, 89, 63, 118, 28, 32, 40, 2...  29.256948   
2      [104, 138, 64, 107, 85, 63, 115, 28, 32, 34, 1...   1.040782   
3      [125, 153, 80, 114, 96, 76, 125, 40, 35, 46, 3...   3.047766   
4      [134, 168, 97,

In [5]:
with open(f'Dataset/label_2100.info', encoding='utf-8') as f:
    label2idx = eval(f.read())
labels = list(label2idx.keys())
label2idx

{'识货': 0,
 '雪球股票': 1,
 '学霸君': 2,
 '车轮违章查询': 3,
 '猫眼': 4,
 'QQ': 5,
 '新浪财经': 6,
 '壹钱包': 7,
 '交管12123': 8,
 '挖财记账': 9,
 '摩拜单车': 10,
 '疯读小说': 11,
 '神州租车': 12,
 '随行付Plus': 13,
 '金山词霸': 14,
 '货拉拉-拉货搬家': 15,
 '第五人格': 16,
 '轻颜相机': 17,
 '华住会': 18,
 '天眼查企业查询': 19,
 '天天基金': 20,
 '中国银行': 21,
 '同花顺': 22,
 '微信': 23,
 '菜鸟裹裹': 24,
 '\xa0猎豹安全大师': 25,
 '买单吧': 26,
 '皇室战争': 27,
 '无忧行': 28,
 '曹操出行': 29,
 '和地图': 30,
 '追书神器': 31,
 '安逸花': 32,
 '运满满司机': 33,
 '蚂蜂窝自由行': 34,
 '中国建设银行': 35,
 '国美': 36,
 '美篇': 37,
 'WiFi万能钥匙': 38,
 '饿了么星选': 39,
 '七猫免费小说': 40,
 '自动点击器': 41,
 '360清理大师': 42,
 '美拍': 43,
 '有道翻译官': 44,
 '每日优鲜': 45,
 '抖音短视频': 46,
 '360借条-贷款分期借款': 47,
 '交通银行': 48,
 '懂车帝': 49,
 '百度手机助手': 50,
 '腾讯视频': 51,
 '红果免费小说': 52,
 '美团外卖': 53,
 '来分期': 54,
 '天眼查': 55,
 '移动惠生活': 56,
 '全民K歌': 57,
 '小猿口算': 58,
 '哈啰出行': 59,
 '应用宝': 60,
 '云闪付': 61,
 '省钱快报': 62,
 '贪吃蛇大作战®': 63,
 '豌豆荚': 64,
 '网易云音乐': 65,
 '小米有品': 66,
 '拼多多': 67,
 'luckin coffee': 68,
 '阳光惠生活': 69,
 '夸克': 70,
 '马上金融': 71,
 'PicsArt美易照片编辑': 72,
 '萤石云视频': 73,
 '企

In [6]:
df_known = df[df['label'].isin(label2idx.keys())]
df_unknown = df[~df['label'].isin(label2idx.keys())]
df_known.shape, df_unknown.shape

((52000, 17), (23000, 17))

In [10]:
labels_ = list(df_unknown['label'].value_counts().index)
label2idx_ = dict(zip(labels_,range(len(labels_))))
len(label2idx_)

46

In [11]:
y_test = df_known['label'].apply(lambda x:label2idx[x]).to_numpy()

In [20]:
# rootdir_cnn = 'model_trained/clsText-ResNet_202307140956'
# rootdir_rnn = 'model_trained/multiPS-RNN_202307230353'

rootdir_cnn = 'model_trained/Text-Net'
rootdir_rnn = 'model_trained/PS-Net'

In [21]:
from Text_Net import ResNet
from PS_Net import RNN
import os
import joblib

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model_text = ResNet(class_num=104,out_dim=16,block_num=2).to(device)
model_text.load_state_dict(torch.load(os.path.join(rootdir_cnn,'best.pt'),map_location=device))
model_text.eval()

model_ps = RNN(class_num=104,out_dim=16,hidden_size=128).to(device)
model_ps.load_state_dict(torch.load(os.path.join(rootdir_rnn,'best.pt'),map_location=device))
model_ps.eval()


RNN(
  (embedding): Embedding(3001, 128, padding_idx=1500)
  (rnn): GRU(128, 128, num_layers=3, dropout=0.2, bidirectional=True)
  (dnn): Sequential(
    (0): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=768, out_features=16, bias=True)
  )
  (cls): Sequential(
    (0): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=104, bias=True)
    (3): Softmax(dim=-1)
  )
)

In [22]:
def padding(load, MAXLEN=784, padding_idx=0x100):
    if len(load)>=MAXLEN:
        return load[0:MAXLEN]
    else:
        return load+[padding_idx]*(MAXLEN-len(load))

In [23]:
from tqdm import tqdm

In [24]:
X_upload = df_known['upload'].apply(padding).tolist()
X_download = df_known['download'].apply(padding).tolist()

p_text = []
BATCH_SIZE = 128
for i in tqdm(range(0,len(df_known),BATCH_SIZE)):
    tmp = model_text(
        x_up=torch.tensor(X_upload[i:i+BATCH_SIZE]).long().to(device),
        x_down=torch.tensor(X_download[i:i+BATCH_SIZE]).long().to(device)
    ).detach().tolist()
    p_text += tmp
p_text = np.array(p_text)

p_text.shape

100%|██████████| 407/407 [00:10<00:00, 40.46it/s]


(52000, 104)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = p_text.argmax(axis=1)

print(accuracy_score(y_true=y_test,y_pred=y_pred))
print(confusion_matrix(y_true=y_test,y_pred=y_pred))
print(classification_report(y_true=y_test,y_pred=y_pred,digits=4,target_names=labels))

0.9507884615384615
[[498   0   0 ...   0   0   0]
 [  0 498   0 ...   0   0   0]
 [  0   0 496 ...   0   0   0]
 ...
 [  0   0   0 ... 488   0   0]
 [  0   0   0 ...   0 420   0]
 [  0   0   0 ...   0   0 458]]
               precision    recall  f1-score   support

           识货     1.0000    0.9960    0.9980       500
         雪球股票     0.9980    0.9960    0.9970       500
          学霸君     1.0000    0.9920    0.9960       500
       车轮违章查询     1.0000    0.9760    0.9879       500
           猫眼     0.9960    0.9920    0.9940       500
           QQ     0.6738    0.8840    0.7647       500
         新浪财经     1.0000    0.9920    0.9960       500
          壹钱包     0.9980    0.9920    0.9950       500
      交管12123     1.0000    0.9540    0.9765       500
         挖财记账     0.9919    0.9740    0.9828       500
         摩拜单车     0.9775    0.9560    0.9666       500
         疯读小说     0.9979    0.9700    0.9838       500
         神州租车     0.9960    0.9900    0.9930       500
      随行付Plus     

In [18]:
pd.DataFrame(confusion_matrix(y_true=y_test,y_pred=y_pred),index=labels,columns=labels).to_csv(f'result\\text_CM.csv')
pd.DataFrame(classification_report(y_true=y_test,y_pred=y_pred,target_names=labels,output_dict=True)).transpose().to_csv(f'result\\text_report.csv')

In [26]:
from torch.nn.utils.rnn import pad_sequence

MAXLEN =256

path = df_known['packets'].apply(lambda x:torch.tensor(
    [[p['iat'], p['l'], p['b'], 1 if p['d'] == '>' else -1] for i,p in enumerate(x[0:MAXLEN])]
)).tolist()
path_len = df_known['packets'].apply(lambda x:min(len(x),MAXLEN)).tolist()

p_ps = []
for i in tqdm(range(0,len(df_known),BATCH_SIZE)):
    tmp = model_ps(
        path=pad_sequence(path[i:i+BATCH_SIZE],batch_first=True).float().to(device),
        path_len=torch.tensor(path_len[i:i+BATCH_SIZE])
    ).detach().tolist()
    p_ps += tmp
p_ps = np.array(p_ps)
p_ps.shape

100%|██████████| 407/407 [00:15<00:00, 25.75it/s]


(52000, 104)

In [27]:
y_pred = p_ps.argmax(axis=1)

print(accuracy_score(y_true=y_test,y_pred=y_pred))
print(confusion_matrix(y_true=y_test,y_pred=y_pred))
print(classification_report(y_true=y_test,y_pred=y_pred,digits=4,target_names=labels))

0.9052692307692307
[[498   0   0 ...   0   0   0]
 [  0 496   0 ...   0   0   0]
 [  0   0 490 ...   2   0   0]
 ...
 [  0   0   1 ... 489   0   0]
 [  0   0   0 ...   0 428   1]
 [  0   0   0 ...   0   0 405]]
               precision    recall  f1-score   support

           识货     0.9980    0.9960    0.9970       500
         雪球股票     1.0000    0.9920    0.9960       500
          学霸君     0.9959    0.9800    0.9879       500
       车轮违章查询     0.9938    0.9620    0.9776       500
           猫眼     0.9492    0.9720    0.9605       500
           QQ     0.7287    0.6660    0.6959       500
         新浪财经     0.9796    0.9580    0.9687       500
          壹钱包     0.9939    0.9760    0.9849       500
      交管12123     0.9916    0.9480    0.9693       500
         挖财记账     0.9811    0.9360    0.9580       500
         摩拜单车     0.9458    0.9420    0.9439       500
         疯读小说     0.9710    0.9380    0.9542       500
         神州租车     0.9081    0.9680    0.9371       500
      随行付Plus     

In [ ]:
pd.DataFrame(confusion_matrix(y_true=y_test,y_pred=y_pred),index=labels,columns=labels).to_csv(f'result\\ps_CM.csv')
pd.DataFrame(classification_report(y_true=y_test,y_pred=y_pred,target_names=labels,output_dict=True)).transpose().to_csv(f'result\\ps_report.csv')

In [30]:
features = ['bytes_out', 'pkts_out', 'bytes_in', 'pkts_in', 'dur']

In [28]:
rootdir_base = 'model_trained/Meta-RF.joblib'
model_base = joblib.load(rootdir_base)

In [31]:
p_base = model_base.predict_proba(df_known[features])

In [32]:
y_pred = p_base.argmax(axis=1)
print(accuracy_score(y_true=y_test,y_pred=y_pred))
print(confusion_matrix(y_true=y_test,y_pred=y_pred))
print(classification_report(y_true=y_test,y_pred=y_pred,digits=4,target_names=labels))

0.892673076923077
[[498   0   0 ...   0   0   0]
 [  0 479   0 ...   0   0   0]
 [  0   0 490 ...   0   0   0]
 ...
 [  0   0   0 ... 488   0   0]
 [  0   0   0 ...   0 496   0]
 [  0   0   0 ...   0   0 488]]
               precision    recall  f1-score   support

           识货     0.9960    0.9960    0.9960       500
         雪球股票     0.9466    0.9580    0.9523       500
          学霸君     0.9919    0.9800    0.9859       500
       车轮违章查询     0.9654    0.9480    0.9566       500
           猫眼     0.8721    0.9140    0.8926       500
           QQ     0.7349    0.6320    0.6796       500
         新浪财经     0.9692    0.9440    0.9564       500
          壹钱包     0.9919    0.9800    0.9859       500
      交管12123     0.9938    0.9620    0.9776       500
         挖财记账     0.8827    0.8280    0.8545       500
         摩拜单车     0.8727    0.8500    0.8612       500
         疯读小说     0.9676    0.8960    0.9304       500
         神州租车     0.9025    0.8700    0.8859       500
      随行付Plus     0

In [ ]:
pd.DataFrame(confusion_matrix(y_true=y_test,y_pred=y_pred),index=labels,columns=labels).to_csv(f'result\\base_CM.csv')
pd.DataFrame(classification_report(y_true=y_test,y_pred=y_pred,target_names=labels,output_dict=True)).transpose().to_csv(f'result\\base_report.csv')

In [33]:
X_upBD, X_downBD = np.array(df_known['upBD'].tolist()), np.array(df_known['downBD'].tolist())

X_upBD_ = np.nan_to_num(X_upBD / X_upBD.sum(axis=1)[:, np.newaxis])
X_downBD_ = np.nan_to_num(X_downBD / X_downBD.sum(axis=1)[:, np.newaxis])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_18260\3838066302.py:3: RuntimeWarning: invalid value encountered in true_divide
  X_upBD_ = np.nan_to_num(X_upBD / X_upBD.sum(axis=1)[:, np.newaxis])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_18260\3838066302.py:4: RuntimeWarning: invalid value encountered in true_divide
  X_downBD_ = np.nan_to_num(X_downBD / X_downBD.sum(axis=1)[:, np.newaxis])


In [34]:
X_BD_count = np.concatenate([X_upBD, X_downBD], axis=1)
X_BD_dist = np.concatenate([X_upBD_, X_downBD_], axis=1)
X_BD_count.shape, X_BD_dist.shape

((52000, 512), (52000, 512))

In [35]:
rootdir_BD = 'model_BD/BD-boost.joblib'
model_BD = joblib.load(rootdir_BD)

In [36]:
p_BD = model_BD.predict_proba(X_BD_dist)

In [37]:
y_pred = p_BD.argmax(axis=1)
print(accuracy_score(y_true=y_test,y_pred=y_pred))
print(confusion_matrix(y_true=y_test,y_pred=y_pred))
print(classification_report(y_true=y_test,y_pred=y_pred,digits=4,target_names=labels))

0.9103269230769231
[[497   0   0 ...   0   0   0]
 [  0 446   0 ...   0   0   0]
 [  0   0 484 ...   0   0   0]
 ...
 [  0   0   0 ... 484   0   0]
 [  0   0   0 ...   0 485   0]
 [  0   0   0 ...   0   1 488]]
               precision    recall  f1-score   support

           识货     1.0000    0.9940    0.9970       500
         雪球股票     0.9370    0.8920    0.9139       500
          学霸君     0.9938    0.9680    0.9807       500
       车轮违章查询     0.9677    0.9000    0.9326       500
           猫眼     0.9654    0.9480    0.9566       500
           QQ     0.7821    0.7180    0.7487       500
         新浪财经     0.9879    0.9820    0.9850       500
          壹钱包     0.9980    0.9800    0.9889       500
      交管12123     0.9979    0.9600    0.9786       500
         挖财记账     0.9893    0.9280    0.9577       500
         摩拜单车     0.6696    0.7740    0.7180       500
         疯读小说     0.9705    0.9200    0.9446       500
         神州租车     0.9388    0.9200    0.9293       500
      随行付Plus     

In [38]:
pd.DataFrame(confusion_matrix(y_true=y_test,y_pred=y_pred),index=labels,columns=labels).to_csv(f'result\\BD_CM.csv')
pd.DataFrame(classification_report(y_true=y_test,y_pred=y_pred,target_names=labels,output_dict=True)).transpose().to_csv(f'result\\BD_report.csv')

In [95]:
y_pred = (0.38*p_base + 0.24*p_BD + 0.27*p_text + 0.11*p_ps).argmax(axis=1) # 0.9755769
print(accuracy_score(y_true=y_test,y_pred=y_pred))
print(confusion_matrix(y_true=y_test,y_pred=y_pred))
print(classification_report(y_true=y_test,y_pred=y_pred,digits=4,target_names=labels))

0.9755961538461538
[[498   0   0 ...   0   0   0]
 [  0 499   0 ...   0   0   0]
 [  0   0 496 ...   0   0   0]
 ...
 [  0   0   0 ... 498   0   0]
 [  0   0   0 ...   0 496   0]
 [  0   0   0 ...   0   0 496]]
               precision    recall  f1-score   support

           识货     1.0000    0.9960    0.9980       500
         雪球股票     0.9980    0.9980    0.9980       500
          学霸君     1.0000    0.9920    0.9960       500
       车轮违章查询     1.0000    0.9780    0.9889       500
           猫眼     0.9960    0.9920    0.9940       500
           QQ     0.8463    0.8920    0.8685       500
         新浪财经     1.0000    0.9920    0.9960       500
          壹钱包     1.0000    0.9920    0.9960       500
      交管12123     1.0000    0.9700    0.9848       500
         挖财记账     0.9939    0.9760    0.9849       500
         摩拜单车     0.9816    0.9620    0.9717       500
         疯读小说     0.9959    0.9720    0.9838       500
         神州租车     0.9980    0.9880    0.9930       500
      随行付Plus     

In [90]:
pd.DataFrame(confusion_matrix(y_true=y_test,y_pred=y_pred),index=labels,columns=labels).to_csv(f'result\\CM.csv')
pd.DataFrame(classification_report(y_true=y_test,y_pred=y_pred,target_names=labels,output_dict=True)).transpose().to_csv(f'result\\report.csv')